### ISSUE TITLE
read clustering error

### ISSUE THREAD

**Issue by ajinkyakhilari** [genomicsITER/NanoCLUST#11]
Error executing process > 'read_clustering (1)'

Caused by:
  Process `read_clustering (1)` terminated with an error exit status (1)

Command executed [/NanoporeTools/NanoCLUST/templates/umap_hdbscan.py]:

  #!/usr/bin/env python
  
  import numpy as np
  import umap
  import matplotlib.pyplot as plt
  from sklearn import decomposition
  import random
  import pandas as pd
  import hdbscan
  
  df = pd.read_csv("freqs.txt", delimiter="	")
  
  #UMAP
  motifs = [x for x in df.columns.values if x not in ["read", "length"]]
  X = df.loc[:,motifs]
  X_embedded = umap.UMAP(n_neighbors=15, min_dist=0.1, verbose=2).fit_transform(X)
  
  df_umap = pd.DataFrame(X_embedded, columns=["D1", "D2"])
  umap_out = pd.concat([df["read"], df["length"], df_umap], axis=1)
  
  #HDBSCAN
  X = umap_out.loc[:,["D1", "D2"]]
  umap_out["bin_id"] = hdbscan.HDBSCAN(min_cluster_size=int(50), cluster_selection_epsilon=int(0.5)).fit_predict(X)
  
  #PLOT
  plt.figure(figsize=(20,20))
  plt.scatter(X_embedded[:, 0], X_embedded[:, 1], c=umap_out["bin_id"], cmap='Spectral', s=1)
  plt.xlabel("UMAP1", fontsize=18)
  plt.ylabel("UMAP2", fontsize=18)
  plt.gca().set_aspect('equal', 'datalim')
  plt.title("Projecting " + str(len(umap_out['bin_id'])) + " reads. " + str(len(umap_out['bin_id'].unique())) + " clusters generated by HDBSCAN", fontsize=18)
  
  for cluster in np.sort(umap_out['bin_id'].unique()):
      read = umap_out.loc[umap_out['bin_id'] == cluster].iloc[0]
      plt.annotate(str(cluster), (read['D1'], read['D2']), weight='bold', size=14)
  
  plt.savefig('hdbscan.output.png')
  umap_out.to_csv("hdbscan.output.tsv", sep="	", index=False)

Command exit status:
  1

Command output:
  UMAP(verbose=2)
  Construct fuzzy simplicial set
  Wed Jul 22 18:14:19 2020 Finding Nearest Neighbors
  Wed Jul 22 18:14:19 2020 Building RP forest with 15 trees
  Wed Jul 22 18:14:23 2020 NN descent for 15 iterations
  	 0  /  15
  	 1  /  15
  	 2  /  15
  	 3  /  15
  	 4  /  15
  	 5  /  15
  	 6  /  15
  	 7  /  15
  	 8  /  15
  	 9  /  15
  	 10  /  15
  	 11  /  15
  	 12  /  15
  	 13  /  15
  	 14  /  15
  Wed Jul 22 18:14:58 2020 Finished Nearest Neighbor Search

Command error:
  Traceback (most recent call last):
    File ".command.sh", line 16, in <module>
      X_embedded = umap.UMAP(n_neighbors=15, min_dist=0.1, verbose=2).fit_transform(X)
    File "/NanoporeTools/Bovine_Mastitis_Project/P4_LSK109/p4_LSK109/nanoclust/work/conda/read_clustering-5be9e67ee159b7a180825e360a9ef1d5/lib/python3.8/site-packages/umap/umap_.py", line 1960, in fit_transform
      self.fit(X, y)
    File "/NanoporeTools/Bovine_Mastitis_Project/P4_LSK109/p4_LSK109/nanoclust/work/conda/read_clustering-5be9e67ee159b7a180825e360a9ef1d5/lib/python3.8/site-packages/umap/umap_.py", line 1781, in fit
      self._search_graph.transpose()
    File "/NanoporeTools/Bovine_Mastitis_Project/P4_LSK109/p4_LSK109/nanoclust/work/conda/read_clustering-5be9e67ee159b7a180825e360a9ef1d5/lib/python3.8/site-packages/scipy/sparse/lil.py", line 437, in transpose
      return self.tocsr(copy=copy).transpose(axes=axes, copy=False).tolil(copy=False)
    File "/NanoporeTools/Bovine_Mastitis_Project/P4_LSK109/p4_LSK109/nanoclust/work/conda/read_clustering-5be9e67ee159b7a180825e360a9ef1d5/lib/python3.8/site-packages/scipy/sparse/lil.py", line 462, in tocsr
      _csparsetools.lil_get_lengths(self.rows, indptr[1:])
    File "_csparsetools.pyx", line 109, in scipy.sparse._csparsetools.lil_get_lengths
    File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
    File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
  TypeError: a bytes-like object is required, not 'list'

Work dir:
  /NanoporeTools/Bovine_Mastitis_Project/P4_LSK109/p4_LSK109/nanoclust/work/bd/409eb66eca121aada74eafb4a2e7e3

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by genomicsITER** [comment]
Hi

I've seen that you are using conda envs to run the pipeline and it worked until the relative abundance outputs. We have seen that conda envs may cause trouble in some runs, specifically in the UMAP process. If you experience these issues we'd recommend the Docker option, which pull tested Docker images for process execution.

**Comment by genomicsITER** [comment]
#12
