### ISSUE TITLE
run test fail

### ISSUE THREAD

**Issue by vesperlight2** [genomicsITER/NanoCLUST#20]
when run
nextflow run ~/software/NanoCLUST/main.nf -profile test,docker
fails with:

N E X T F L O W  ~  version 20.10.0
Launching `/home/azshara/software/NanoCLUST/main.nf` [lonely_sinoussi] - revision: c3b5ee2f3d
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
----------------------------------------------------
      _   __                     ________    __  _____________
     / | / /___ _____  ____     / ____/ /   / / / / ___/_  __/
    /  |/ / __ `/ __ \/ __ \   / /   / /   / / / /\__ \ / /
   / /|  / /_/ / / / / /_/ /  / /___/ /___/ /_/ /___/ // /
  /_/ |_/\__,_/_/ /_/\____/   \____/_____/\____//____//_/

  NanoCLUST v1.0dev
----------------------------------------------------
Run Name          : lonely_sinoussi
Reads             : /home/azshara/software/NanoCLUST/test_datasets/mock4_run3bc08_5000.fastq
Max Resources     : 128 GB memory, 16 cpus, 10d time per job
Container         : docker - [:]
Output dir        : ./results
Launch dir        : /home/azshara
Working dir       : /home/azshara/work
Script dir        : /home/azshara/software/NanoCLUST
User              : azshara
Config Profile    : test,docker
Config Description: Minimal test dataset to check pipeline function
----------------------------------------------------
executor >  local (38)
[f8/8f1bd5] process > QC (1)                   [100%] 1 of 1 ✔
[dd/348f4d] process > fastqc (1)               [100%] 1 of 1 ✔
[a2/fef066] process > kmer_freqs (1)           [100%] 1 of 1 ✔
[a9/d714f6] process > read_clustering (1)      [100%] 1 of 1 ✔
[93/54a059] process > split_by_cluster (1)     [100%] 1 of 1 ✔
[7c/acb0eb] process > read_correction (4)      [100%] 8 of 8 ✔
[01/f7adb8] process > draft_selection (6)      [100%] 8 of 8 ✔
[d6/9be817] process > racon_pass (7)           [100%] 8 of 8 ✔
[77/ce919c] process > medaka_pass (8)          [  0%] 0 of 8
[-        ] process > consensus_classification -
[-        ] process > join_results             -
[-        ] process > get_abundances           -
[-        ] process > plot_abundances          -
[db/83f799] process > output_documentation     [100%] 1 of 1 ✔
Error executing process > 'medaka_pass (3)'

Caused by:
  Missing output file(s) `consensus_medaka.fasta/consensus.fasta` expected by process `medaka_pass (3)`

Command executed:

  if medaka_consensus -i corrected_reads.correctedReads.fasta -d racon_consensus.fasta -o consensus_medaka.fasta -t 4 -m r941_min_high_g303 ; then
     echo "Command succeeded"
  else
     cat racon_consensus.fasta > consensus_medaka.fasta
  fi

Command exit status:
  0

Command output:
  (empty)

Command error:

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 39, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/models.py", line 58, in resolve_model
      " the internet and try again.".format(model))
  medaka.models.DownloadError: The model file for r941_min_high_g303 is not already installed and could not be downloaded. Check you are connected to the internet and try again.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/medaka_pass/bin/medaka", line 11, in <module>
      sys.exit(main())
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 612, in main
      args = parser.parse_args()
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1734, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1954, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1931, in consume_positionals
      take_action(action, args)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1137, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1954, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1931, in consume_positionals
      take_action(action, args)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1137, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
executor >  local (38)
[f8/8f1bd5] process > QC (1)                   [100%] 1 of 1 ✔
[dd/348f4d] process > fastqc (1)               [100%] 1 of 1 ✔
[a2/fef066] process > kmer_freqs (1)           [100%] 1 of 1 ✔
[a9/d714f6] process > read_clustering (1)      [100%] 1 of 1 ✔
[93/54a059] process > split_by_cluster (1)     [100%] 1 of 1 ✔
[7c/acb0eb] process > read_correction (4)      [100%] 8 of 8 ✔
[01/f7adb8] process > draft_selection (6)      [100%] 8 of 8 ✔
[d6/9be817] process > racon_pass (7)           [100%] 8 of 8 ✔
[ba/db44e5] process > medaka_pass (1)          [ 14%] 1 of 7, failed: 1
[-        ] process > consensus_classification -
[-        ] process > join_results             -
[-        ] process > get_abundances           -
[-        ] process > plot_abundances          -
[db/83f799] process > output_documentation     [100%] 1 of 1 ✔
Error executing process > 'medaka_pass (3)'

Caused by:
  Missing output file(s) `consensus_medaka.fasta/consensus.fasta` expected by process `medaka_pass (3)`

Command executed:

  if medaka_consensus -i corrected_reads.correctedReads.fasta -d racon_consensus.fasta -o consensus_medaka.fasta -t 4 -m r941_min_high_g303 ; then
     echo "Command succeeded"
  else
     cat racon_consensus.fasta > consensus_medaka.fasta
  fi

Command exit status:
  0

Command output:
  (empty)

Command error:

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 39, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/models.py", line 58, in resolve_model
      " the internet and try again.".format(model))
  medaka.models.DownloadError: The model file for r941_min_high_g303 is not already installed and could not be downloaded. Check you are connected to the internet and try again.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/conda/envs/medaka_pass/bin/medaka", line 11, in <module>
      sys.exit(main())
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 612, in main
      args = parser.parse_args()
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1734, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1954, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1931, in consume_positionals
      take_action(action, args)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1137, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1954, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1931, in consume_positionals
      take_action(action, args)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1137, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1972, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1912, in consume_optional
      take_action(action, args, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 42, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: The model file for r941_min_high_g303 is not already installed and could not be downloaded. Check you are connected to the internet and try again..

Work dir:
  /home/azshara/work/ce/72aa71bf8bf6c6d1161b33d8892b72

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by genomicsITER** [comment]
Hi, 

Thank you for opening the issue and sorry for the late response.

It seems that default config files (containing the needed default parameters) is not loading properly. You can specify the nextflow.config inside NanoCLUST dir manually using `-c` parameter with the absolute path to your .conf file.

Anyway, We recommend to run the pipeline inside its directory and specify the relative path to the `main.nf` file:

nextflow run main.nf -profile test,<conda/docker>

Netxflow can be either added to the PATH or be installed under the NanoCLUST dir and run with `./nextflow run ...`

**Comment by Meghana9854** [comment]
Hi, 

I've installed conda and nextflow but when I run the line 
nextflow run main.nf -profile test,<conda/docker>
I get an error saying "Cannot find script file: main.nf"
Where can I find the main.nf file to provide the relative path?

Thanks, 

Meghana

**Comment by ramc80** [comment]
I am also getting the following error while running NanoCLUST test run. Please help how to fix


Error executing process > 'medaka_pass (1)'

Caused by:
  Missing output file(s) `consensus_medaka.fasta/consensus.fasta` expected by process `medaka_pass (1)`

Command executed:

  if medaka_consensus -i corrected_reads.correctedReads.fasta -d racon_consensus.fasta -o consensus_medaka.fasta -t 4 -m r941_min_high_g303 ; then
     echo "Command succeeded"
  else
     cat racon_consensus.fasta > consensus_medaka.fasta
  fi

Command exit status:
  0

Command output:
  TF_CPP_MIN_LOG_LEVEL is set to '3'
  Checking program versions
  This is medaka 1.11.3

Work dir:
  /home/jayaram/NanoCLUST/work/b3/c9b7bf4c1a19fe7c18000ebf402022

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
