### ISSUE TITLE
Missing output file(s) `consensus_medaka.fasta/consensus.fasta` expected by process `medaka_pass (3)`

### ISSUE THREAD

**Issue by Syutenjyo** [genomicsITER/NanoCLUST#44]
I have just met a problem.
Please help me.

executor >  local (28)
[76/736bf5] process > QC (1)                   [100%] 1 of 1 ✔
[74/e820fa] process > fastqc (1)               [100%] 1 of 1 ✔
[c5/0fca5a] process > kmer_freqs (1)           [100%] 1 of 1 ✔
[8d/4fc55f] process > read_clustering (1)      [100%] 1 of 1 ✔
[d1/a50527] process > split_by_cluster (1)     [100%] 1 of 1 ✔
[42/5f1770] process > read_correction (6)      [100%] 6 of 6 ✔
[3a/e0fc08] process > draft_selection (6)      [100%] 6 of 6 ✔
[73/3a41d1] process > racon_pass (6)           [100%] 6 of 6 ✔
[5d/fe60c2] process > medaka_pass (3)          [ 50%] 3 of 6, failed: 1
[-        ] process > consensus_classification [  0%] 0 of 2
[-        ] process > join_results             -
[-        ] process > get_abundances           -
[-        ] process > plot_abundances          -
[18/a8674b] process > output_documentation     [100%] 1 of 1 ✔
Error executing process > 'medaka_pass (3)'

Caused by:
  Missing output file(s) `consensus_medaka.fasta/consensus.fasta` expected by process `medaka_pass (3)`

Command executed:

  if medaka_consensus -i corrected_reads.correctedReads.fasta -d racon_consensus.fasta -o consensus_medaka.fasta -t 4 -m r941_min_high_g303 ; then
     echo "Command succeeded"
  else
     cat racon_consensus.fasta > consensus_medaka.fasta
  fi

Command exit status:
  0

Command output:
  (empty)

Command error:
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 39, in __call__
      model_fp = medaka.models.resolve_model(val)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/models.py", line 58, in resolve_model
      " the internet and try again.".format(model))
  medaka.models.DownloadError: The model file for r941_min_high_g303 is not already installed and could not be downloaded. Check you are connected to the internet and try again.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/opt/conda/envs/medaka_pass/bin/medaka", line 11, in <module>
      sys.exit(main())
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 612, in main
      args = parser.parse_args()
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1734, in parse_args
      args, argv = self.parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1954, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1931, in consume_positionals
      take_action(action, args)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1137, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1954, in _parse_known_args
      positionals_end_index = consume_positionals(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1931, in consume_positionals
      take_action(action, args)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1137, in __call__
      subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1766, in parse_known_args
      namespace, args = self._parse_known_args(args, namespace)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1972, in _parse_known_args
      start_index = consume_optional(start_index)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1912, in consume_optional
      take_action(action, args, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/argparse.py", line 1840, in take_action
      action(self, namespace, argument_values, option_string)
    File "/opt/conda/envs/medaka_pass/lib/python3.6/site-packages/medaka/medaka.py", line 42, in __call__
      raise RuntimeError(msg.format(self.dest, str(e)))
  RuntimeError: Error validating model from '--model' argument: The model file for r941_min_high_g303 is not already installed and could not be downloaded. Check you are connected to the internet and try again..

Work dir:
  /home/syu/nano/results/work/5d/fe60c2c93072c4fdeab8de9a735c6c

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by Thomieh73** [comment]
We encountered the same issue. Medaka stalls because it wants the model file. It is unclear why it happens.

**Comment by Thomieh73** [comment]
We have not solved this issue. What is strange is that this is an issue a colleague of mine is experiencing. She used the fork of this repo that I created. We both tried to run the pipeline on the same HPC cluster with exactly the same commands. The only thing that is different is the location of our nextflow working directory. 

one thing we tried was to copy the medaka singularity image, that I created when running the pipeline, to the workdirectory of my colleague. . For me the medaka step worked with that image. However, for my colleague, it failed again with the same error.

This is odd behaviour. The original submitter from this issue @Syutenjyo has probably had this when using your docker image. So it is not due to singularity, but something with the docker image.

**Comment by miangher** [comment]
hello! 
I'm having the same problem! Did you manage to solve this? do you have a solution?
Thank you very much for your answer!

**Comment by Nakanishi-T** [comment]
I also have the same problem. In my case, it can run for the first fastq input, but have this issue on second and third files.
