### ISSUE TITLE
swap memory issues

### ISSUE THREAD

**Issue by mawa86** [genomicsITER/NanoCLUST#51]
Hi

Im having an issue running the pipeline on an Ubuntu 18.04 LTS machine.
Im running it through a Docker profile as suggested, however it looks like there is a problem in memory allocation as the whole process stops as soon as the kmer_freqs process initiates (see the error message below)

```
Error executing process > 'kmer_freqs (172)'

Caused by:
  Process `kmer_freqs (172)` terminated with an error exit status (1)

Command executed:

  kmer_freq.py -r BC11_qced_reads_set.fastq > freqs.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Traceback (most recent call last):
    File "/path/to/NanoCLUST/bin/kmer_freq.py", line 244, in <module>
      main(args)
    File "/path7to/NanoCLUST/bin/kmer_freq.py", line 216, in main
      ftype  = check_input_format(args.qced_reads)
    File "/path/to/NanoCLUST/bin/kmer_freq.py", line 207, in check_input_format
      if line[0]=="@":
  UnboundLocalError: local variable 'line' referenced before assignment

Work dir:
  /path/to/NanoCLUST/work/3d/6cfe8a5e749c3a98f56d1ce51b0d91
```

Now Ive tried to look at how to fix memory swap issues on Docker, but I don't seem to come across any good tutorial for a newbie like myself.
Has anyone got a clue what I need to do in order to fix this, or if there is an option in nanoCLUST to set a limit on the amount of processes to run simultaneously?

Appreciate any help

Martin

**Comment by mawa86** [comment]
Ok reading more into this I can see that it seems to call to an error in the python script of the kmer_freq block. Has anyone got any clue?

**Comment by chris-krohn** [comment]
** UPDATE ** 
The below was resolved after using the unfiltered fastq file (i.e. the fastq before filtering with chopper). 
Cheers, Chris


Hi there, 
I have a similar error. The test run `nextflow run main.nf -profile test,docker` ran without errors. But testing on my own fastq failed with below error. The fastq was generated with dorado sup basecalling (first into .bam files then demultiplexed to .fastq files). The fastq was quality filtered with chopper.  Here the first read of this .fastq [filtered.fastq.txt](https://github.com/user-attachments/files/16401749/filtered.fastq.txt). Could this have to do with the header syntax?

On Mac M1 (arm64). Any advice appreciated :). Thanks! 
Chris



 
**Command:** 
`export NXF_VER=22.10.1` (Need to use this version as the later versions gives another error).
`nextflow run main.nf -profile docker  --reads '/path/to/fastq/filtered.fastq' --db "db/16S_ribosomal_RNA" --tax "db/taxdb/"`


**Error message:**
July-28 09:22:09.808 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'kmer_freqs (1)'
Caused by:
  Process `kmer_freqs (1)` terminated with an error exit status (1)

Command executed:

  kmer_freq.py -r filtered_qced_reads_set.fastq > freqs.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  Traceback (most recent call last):
    File "/Users/username/Applications/NanoCLUST-master/bin/kmer_freq.py", line 244, in <module>
      main(args)
    File "/Users/username/Applications/NanoCLUST-master/bin/kmer_freq.py", line 216, in main
      ftype  = check_input_format(args.qced_reads)
    File "/Users/username/Applications/NanoCLUST-master/bin/kmer_freq.py", line 207, in check_input_format
      if line[0]=="@":
  UnboundLocalError: local variable 'line' referenced before assignment
